categories:
  - title: '🚀 New Features'
    labels:
      - 'enhancement'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🛠 Maintenance'
    labels:
      - 'chore'
      - 'refactor'
  - title: '📚 Documentation'
    labels:
      - 'docs'
  - title: '⚡ Performance'
    labels:
      - 'perf'
  - title: '💥 Breaking Changes'
    labels:
      - 'breaking-change'
      - 'major'
exclude-labels:
  - 'skip-changelog'
exclude-contributors:
  - 'app/dependabot'
template: |
  ## What's Changed

  $CHANGES
version-resolver:
  major:
    labels: ['major', 'breaking-change']
  minor:
    labels: ['minor' , 'feat', 'enhancement']
  patch:
    labels: ['patch', 'bug', 'chore', 'fix', 'refactor', 'docs', 'perf']
  default: patch

autolabeler:
  - label: 'chore'
    files:
      - '*.md'
      - '.gitignore' 
      - '.editorconfig'
      - '.vscode/**'
      - '**/*.test'
      - '**/*.log'
    branch:
      - '/docs{0,1}\/.+/'
      - '/chore\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
      - '/enhancement\/.+/'
      - '/feat\/.+/'
    body:
      - '/JIRA-[0-9]{1,4}/'
