name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 New Features'
    labels:
      - 'enhancement'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🛠 Maintenance'
    labels:
      - 'chore'
      - 'refactor'
  - title: '📚 Documentation'
    labels:
      - 'docs'
  - title: '⚡ Performance'
    labels:
      - 'perf'
  - title: '💥 Breaking Changes'
    labels:
      - 'breaking-change'
      - 'major'
template: |
  ## What's Changed

  $CHANGES
version-resolver:
  major:
    labels: ['major', 'breaking-change']
  minor:
    labels: ['minor' , 'feat', 'enhancement']
  patch:
    labels: ['patch', 'bug', 'chore', 'fix', 'refactor', 'docs', 'perf']