name: Build eBrick Binaries

on:
  push:
    paths:
      - '**/*.go'       # Go source files
      - '**/*.tmpl'     # Template files
      - '**/*.tpl'      # Template files
      - 'go.mod'        # Dependency management file
      - 'go.sum'        # Dependency lock file
      - 'config/**/*.yaml'  # YAML config files
      - 'config/**/*.yml'  # YAML config files
      - 'config/**/*.json'  # JSON config files
      - '.github/workflows/*'  # CI/CD workflow files
  pull_request:
    paths:
      - '**/*.go'       # Go source files
      - '**/*.tmpl'     # Template files
      - '**/*.tpl'      # Template files
      - 'go.mod'        # Dependency management file
      - 'go.sum'        # Dependency lock file
      - 'config/**/*.yaml'  # YAML config files
      - 'config/**/*.yml'  # YAML config files
      - 'config/**/*.json'  # JSON config files
      - '.github/workflows/*'  # CI/CD workflow files
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'

      # Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install dependencies
      - name: Install dependencies
        run: go mod download

      # Build for Linux
      - name: Build for Linux
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ebrick-linux-amd64 ./cmd/ebrick

      # Build for macOS (Intel)
      - name: Build for macOS (Intel)
        run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o ebrick-darwin-amd64 ./cmd/ebrick

      # Build for macOS (M1 ARM64)
      - name: Build for macOS (M1 ARM64)
        run: CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o ebrick-darwin-arm64 ./cmd/ebrick

      # Build for Windows
      - name: Build for Windows
        run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o ebrick-windows-amd64.exe ./cmd/ebrick
