name: Docker Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*' # Trigger the workflow only when a tag matching the pattern is pushed

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image for multiple platforms
      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --tag trinitytechnology/ebrick:${{ github.ref_name }} \
            --tag trinitytechnology/ebrick:latest \
            --push .
