name: Release Drafter
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Draft Release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          token: ${{ secrets.GITHUB_TOKEN }}
